# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    container_name: nginx_laravel9
    build:
      context: .
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "8088:443"
    links:
      - php-fpm

  php-fpm:
    container_name: php_laravel9
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - mysql

  mysql:
    container_name: mysql_laravel9
    image: mysql:8
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    ports:
      - "33062:3306"

  node:
    container_name: node_laravel9
    build:
      context: .
      dockerfile: docker/node/node.docker
    volumes:
      - ./:/var/www
    tty: true

