# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    container_name: nginx_laravel9
    build:
      context: .
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
      # - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "8087:80"
    links:
      - php-fpm

  php-fpm:
    container_name: php_laravel9
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - mysql

  mysql:
    container_name: mysql_laravel_9
    image: mysql:8.3.0
    restart: always
    environment:
      # - "MYSQL_ROOT_PASSWORD=root;"
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    ports:
      - "33062:3306"
    # command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    # expose:
      # Opens port 3306 on the container
      # - '3306'

  app:
    depends_on:
     - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
     - '8080:80'
    environment:
      PMA_HOST: mysql
